INSERT INTO `addproductcategory` (`sysdate`, `entrydate`, `sessionid`, `category`, `status`, `showmode`, `onlinestatus`, `outletcode`, `username`, `code_series`, `outlet`, `store`, `production`, `purchase`, `despatch`, `is_asset`) VALUES (NULL, '2022-02-13', NULL, 'Happy Meals', '0', NULL, '0', NULL, 'Admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO `outletrequisition` (`sysdate`, `entrydate`, `sessionid`, `rcventrydate`, `reqinvoiceno`, `rcvinvoiceno`, `category`, `subcategory`, `innersubcategory`, `pcsreqfrombr`, `pcsrcvfromho`, `wastage`, `productcodeno`, `balanceinhand`, `stockbalancebefore`, `stockbalanceafter`, `unitprice`, `expire`, `status`, `onlinestatus`, `requsername`, `rcvusername`, `unit`, `sellmode`, `prdbelowrange`, `username`, `reqoutletcode`, `rcvoutletcode`, `imagepath`, `extrastatus`, `requisitionby`, `discountstatus`, `vatstatus`, `sdrate`, `poutletcode`, `cprice`, `barcode`, `description`) VALUES (NULL, '2022-11-21', NULL, NULL, NULL, NULL, 'Happy Meals', 'Sandwich Meal', '', NULL, NULL, NULL, '174', '9997', NULL, NULL, '257', '30', '0', '0', NULL, NULL, 'pcs', 'Yes', NULL, '100.A', NULL, NULL, NULL, 'No', NULL, '0', '0', '0', '105', '0', '', NULL);


INSERT INTO `outletrequisition` (`sysdate`, `entrydate`, `sessionid`, `rcventrydate`, `reqinvoiceno`, `rcvinvoiceno`, `category`, `subcategory`, `innersubcategory`, `pcsreqfrombr`, `pcsrcvfromho`, `wastage`, `productcodeno`, `balanceinhand`, `stockbalancebefore`, `stockbalanceafter`, `unitprice`, `expire`, `status`, `onlinestatus`, `requsername`, `rcvusername`, `unit`, `sellmode`, `prdbelowrange`, `username`, `reqoutletcode`, `rcvoutletcode`, `imagepath`, `extrastatus`, `requisitionby`, `discountstatus`, `vatstatus`, `sdrate`, `poutletcode`, `cprice`, `barcode`, `description`) VALUES (NULL, '2022-11-21', NULL, NULL, NULL, NULL, 'Happy Meals', 'Burger Meal (01)', '', NULL, NULL, NULL, '175', '9997', NULL, NULL, '314', '30', '0', '0', NULL, NULL, 'pcs', 'Yes', NULL, '100.A', NULL, NULL, NULL, 'No', NULL, '0', '0', '0', '105', '0', '', NULL);



INSERT INTO `outletrequisition` (`sysdate`, `entrydate`, `sessionid`, `rcventrydate`, `reqinvoiceno`, `rcvinvoiceno`, `category`, `subcategory`, `innersubcategory`, `pcsreqfrombr`, `pcsrcvfromho`, `wastage`, `productcodeno`, `balanceinhand`, `stockbalancebefore`, `stockbalanceafter`, `unitprice`, `expire`, `status`, `onlinestatus`, `requsername`, `rcvusername`, `unit`, `sellmode`, `prdbelowrange`, `username`, `reqoutletcode`, `rcvoutletcode`, `imagepath`, `extrastatus`, `requisitionby`, `discountstatus`, `vatstatus`, `sdrate`, `poutletcode`, `cprice`, `barcode`, `description`) VALUES (NULL, '2022-11-21', NULL, NULL, NULL, NULL, 'Happy Meals', 'Burger Meal (02)', '', NULL, NULL, NULL, '176', '9997', NULL, NULL, '549', '30', '0', '0', NULL, NULL, 'pcs', 'Yes', NULL, '100.A', NULL, NULL, NULL, 'No', NULL, '0', '0', '0', '105', '0', '', NULL);

update`outletrequisition`SET `vatstatus`='5' WHERE `productcodeno` IN ('174','175','176')